name: Atualizar Currículo Lattes

on:
  schedule:
    - cron: "0 6 * * *"   # roda todo dia às 6h UTC
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          pip install --upgrade pip wheel setuptools
          pip install requests pdfplumber

      - name: Atualizar currículo
        run: python atualizar.py

      - name: Commit e push mudanças
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add curriculo.html || true
          git commit -m "Atualização automática do currículo" || true
          git push || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Publicar no GitHub Pages
        uses: peac
